Name: "prometheus"
ChartName: "tools/kube-prometheus-stack"
Category: "Observability"
Description: "Intelops Grafana"
RepoName: "tools"
RepoURL: "https://kube-tarian.github.io/helmrepo-supporting-tools"
Namespace: "observability"
ReleaseName: "prometheus"
Version: "1.0.1"
CreateNamespace: true
PrivilegedNamespace: true
LaunchURL: https://grafana.{{.DomainName}}/login/generic_oauth
LaunchUIDescription: "Intelops Grafana"
LaunchUIIcon: "grafana.svg"
LaunchUIValues:
  grafana:
    grafana.ini:
      auth.generic_oauth:
        enabled: true
        name: Intelops
        allow_sign_up: true
        client_id: "{{.ClientId}}"
        client_secret: "{{.ClientSecret}}"
        scopes: "openid email"
        auth_url: "{{.OAuthBaseURL}}/oauth2/auth"
        token_url: "{{.OAuthBaseURL}}/oauth2/token"
        api_url: "{{.OAuthBaseURL}}/userinfo"
        allow_assign_grafana_admin: true
      server:
       root_url: https://grafana.{{.DomainName}}/
OverrideValues:
  grafana:
    enabled: true
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod-cluster
        kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
      enabled: true
      hosts:
      - "grafana.{{.DomainName}}"
      tls:
      - hosts:
        - "grafana.{{.DomainName}}"
        secretName: cert-grafana
    plugins:
    - vertamedia-clickhouse-datasource
    - grafana-clickhouse-datasource
    sidecar:
      dashboards:
        enabled: true
        folderAnnotation: grafana_folder
        provider:
          foldersFromFilesStructure: true
      datasources:
        enabled: true
  prometheus:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod-cluster
        kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
      enabled: true
      hosts:
      - "prometheus.{{.DomainName}}"
      paths:
      - /
      tls:
      - hosts:
        - "prometheus.{{.DomainName}}"
        secretName: cert-prometheus
    prometheusSpec:
      enableRemoteWriteReceiver: true
      externalLabels:
        cluster_name: capten-controlplane
  alertmanager:
    alertmanagerSpec:
      alertmanagerConfigMatcherStrategy:
        type: None
