Region: "centralindia"
MasterCount:
  - "talos-master1"
  - "talos-master2"
  - "talos-master3"
WorkerCount:
  - "talos-worker1"
  - "talos-worker2"
  - "talos-worker3"
  - "talos-worker4"
  - "talos-worker5"
NICs:
  - "talos-nic-master1"
  - "talos-nic-master2" 
  - "talos-nic-master3"
WorkerNics:
  - "talos-nic-worker1"
  - "talos-nic-worker2"
  - "talos-nic-worker3"
  - "talos-nic-worker4"

InstanceType: "Standard_D4_v3"
PublicIpName:
  - "talos-public-ip-1"
  - "talos-public-ip-2"
  - "talos-public-ip-3"
TraefikHttpPort: 32080
TraefikHttpsPort: 32443
Talosrgname: "talosrg5"
Storagergname: "StoargeRG5"
Storage_account_name: "talosimagesa5"
Talos_imagecont_name: "talosimagecont5"
Talos_cluster_name: "taloscluster5"
Nats_client_port: 31675