Region: "centralindia"
TerraformModulesDirPath: "/home/shifnazarnaz/go/src/github.com/intelops/capten/capten/terraform_modules"
MasterCount:
  - "talos-master1"
  - "talos-master2"
  - "talos-master3"
WorkerCount:
  - "talos-worker1"
  - "talos-worker2"
  - "talos-worker3"
NICs:
  - "talos-nic-master1"
  - "talos-nic-master2" 
  - "talos-nic-master3"
WorkerNics:
  - "talos-nic-worker1"
  - "talos-nic-worker2"
  - "talos-nic-worker3"

InstanceType: "Standard_DS1_v2"
PublicIpName:
  - "talos-public-ip-1"
  - "talos-public-ip-2"
  - "talos-public-ip-3"
TraefikHttpPort: 32080
TraefikHttpsPort: 32443



