DomainName: capten.intelops.app
LoadBalancerHost: ""
CloudService: aws
ClusterType: talos
ClusterCAIssuer: ""
SocialIntegration: "teams"
SlackURL: "slack.com"
SlackChannel: "intelops"
TeamsURL: "teams.com"
